### ISSUE TITLE
issue regarding latest changes

### ISSUE THREAD

**Issue by choper725** [axelmohnen/a2UI5-generic_search_hlp#17]
Hi @axelmohnen 

getting a few errors upon updating to latest commit.

1. 
![image](https://github.com/axelmohnen/a2UI5-generic_search_hlp/assets/129428114/98a6c860-5507-4333-832f-e889f1e068df)

2.
![image](https://github.com/axelmohnen/a2UI5-generic_search_hlp/assets/129428114/1e9451e8-77a9-4b60-89f5-a20580313353)

3. also this table does not exist, in class Z2UI5_CL_TOOL_APP_SHLP_GEN
DATA: lt_dd07v  TYPE dd07v_t,

maybe dd07v_tab is the same ?? dont really know..

4. as of latest pull from a2ui5, client is not passed anymore to factory methods, and need to be removed from caller.

in class:Z2UI5_CL_TOOL_APP_VH_GEN
lines: DATA(lr_popup) = z2ui5_cl_xml_view=>factory_popup( ir_client ).

as in other factory methods in this implementation.

5. how does the deep_sh parameter should work ?? its an idea now or its fully functional ? was testing it out didnt do what i was expecting it.. maybe you can make a quick demo on it or give a DDIC field with SH that it should work on ? i tried on SPRAS, but didnt saw any difference.
im running on abap 7.50 on-prem, btw if thats relevant i suppose.

**Comment by choper725** [comment]
i can try PR wlth fixes if thats ok by you

**Comment by axelmohnen** [comment]
Hi @choper725,
I will have a look.... and provide an update soon.
Thanks,
Axel

**Comment by axelmohnen** [comment]
Hi @choper725,
I issues should be fixed now.
I added a new demo app "Z2UI5_CL_TOOL_APP_12" in order to demonstrate the new "IV_USE_DEEP_SHLP" parameter.
The "deep search" is fully functional. In case the DDIC searchhelp contains search fields where the corresponding data element has a DDIC SHLP maintained or the corresponding domain has some fix values maintained, than if the "IV_USE_DEEP_SHLP" parameter is flagged it will open another generic SHLP or generic value help.
Just give it a try :-)
Thanks,
Axel

**Comment by choper725** [comment]
thx @axelmohnen  ill check it ou!

**Comment by choper725** [comment]
hi @axelmohnen 
still getting error on views creation methods, regarding latest a2ui5 version
![image](https://github.com/axelmohnen/a2UI5-generic_search_hlp/assets/129428114/85b5d8bf-d05b-41da-a7c8-ae714d3e46f1)

**Comment by axelmohnen** [comment]
Hi @choper725,
I removed all erroneous factory calls, due to the latest 2UI5 version, from the demo apps. 
I don't have the latest 2UI5 version in our system yet. That's the reason why I don't have the error....

The demo12 is working, but it was probably not a good example. 
Explanation:
Demo12 was using searchhelp "H_T002". This searchhelp has the field "SPRAS" with data element "SPRAS". Data element "SPRAS" has the searchhelp "H_T002" assigned. This is exactly the same searchhelp. This means, for you it looks that you have to click twice.

I added now the company code searchhelp "H_T001_ME" to demo12. This has the field "BUKRS" and the data element "BUKRS".
The data element "BUKRS" has the searchhelp "C_T001" assigned.

**Comment by choper725** [comment]
ohh i see, thats why double clicking..

great ill check those !!

btw even in older versions client is not mandatory to pass to the view functions

**Comment by AndreaBorgia-Abo** [comment]
table T001 does not exist in NPL / A4H MiniSAP, pull fails

**Comment by axelmohnen** [comment]
Hi @AndreaBorgia-Abo,
could you please retry. I replaced the table t001 in all demos.

**Comment by AndreaBorgia-Abo** [comment]
Pull now works, super fast, thanks.
